//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("http://nlog-project.org/ws/", ClrNamespace="nlogproject.org.ws")]

namespace nlogproject.org.ws
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="events", Namespace="http://nlog-project.org/ws/")]
    public partial class events : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string cliField;
        
        private long btsField;
        
        private nlogproject.org.ws.StringCollection ltsField;
        
        private nlogproject.org.ws.StringCollection strField;
        
        private nlogproject.org.ws.e[] evField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cli
        {
            get
            {
                return this.cliField;
            }
            set
            {
                this.cliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long bts
        {
            get
            {
                return this.btsField;
            }
            set
            {
                this.btsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public nlogproject.org.ws.StringCollection lts
        {
            get
            {
                return this.ltsField;
            }
            set
            {
                this.ltsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public nlogproject.org.ws.StringCollection str
        {
            get
            {
                return this.strField;
            }
            set
            {
                this.strField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public nlogproject.org.ws.e[] ev
        {
            get
            {
                return this.evField;
            }
            set
            {
                this.evField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="StringCollection", Namespace="http://nlog-project.org/ws/", ItemName="l")]
    public class StringCollection : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="e", Namespace="http://nlog-project.org/ws/")]
    public partial class e : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int idField;
        
        private int lvField;
        
        private int lgField;
        
        private long tsField;
        
        private int mField;
        
        private string valField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int lv
        {
            get
            {
                return this.lvField;
            }
            set
            {
                this.lvField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int lg
        {
            get
            {
                return this.lgField;
            }
            set
            {
                this.lgField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public long ts
        {
            get
            {
                return this.tsField;
            }
            set
            {
                this.tsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int m
        {
            get
            {
                return this.mField;
            }
            set
            {
                this.mField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string val
        {
            get
            {
                return this.valField;
            }
            set
            {
                this.valField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://nlog-project.org/ws/", ConfigurationName="ILogReceiverServer")]
public interface ILogReceiverServer
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://nlog-project.org/ws/ILogReceiverServer/ProcessLogMessages", ReplyAction="http://nlog-project.org/ws/ILogReceiverServer/ProcessLogMessagesResponse")]
    void ProcessLogMessages(nlogproject.org.ws.events events);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://nlog-project.org/ws/ILogReceiverServer/ProcessLogMessages", ReplyAction="http://nlog-project.org/ws/ILogReceiverServer/ProcessLogMessagesResponse")]
    System.Threading.Tasks.Task ProcessLogMessagesAsync(nlogproject.org.ws.events events);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILogReceiverServerChannel : ILogReceiverServer, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LogReceiverServerClient : System.ServiceModel.ClientBase<ILogReceiverServer>, ILogReceiverServer
{
    
    public LogReceiverServerClient()
    {
    }
    
    public LogReceiverServerClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LogReceiverServerClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LogReceiverServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LogReceiverServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void ProcessLogMessages(nlogproject.org.ws.events events)
    {
        base.Channel.ProcessLogMessages(events);
    }
    
    public System.Threading.Tasks.Task ProcessLogMessagesAsync(nlogproject.org.ws.events events)
    {
        return base.Channel.ProcessLogMessagesAsync(events);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://aei.polsl.pl/services/logger", ConfigurationName="ILogService")]
public interface ILogService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://aei.polsl.pl/services/logger/ILogService/ReceiveLogS", ReplyAction="http://aei.polsl.pl/services/logger/ILogService/ReceiveLogSResponse")]
    void ReceiveLogS(ServiceLibrary.DbModels.Log.EventLog eventLog);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://aei.polsl.pl/services/logger/ILogService/ReceiveLogS", ReplyAction="http://aei.polsl.pl/services/logger/ILogService/ReceiveLogSResponse")]
    System.Threading.Tasks.Task ReceiveLogSAsync(ServiceLibrary.DbModels.Log.EventLog eventLog);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILogServiceChannel : ILogService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LogServiceClient : System.ServiceModel.ClientBase<ILogService>, ILogService
{
    
    public LogServiceClient()
    {
    }
    
    public LogServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LogServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LogServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LogServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void ReceiveLogS(ServiceLibrary.DbModels.Log.EventLog eventLog)
    {
        base.Channel.ReceiveLogS(eventLog);
    }
    
    public System.Threading.Tasks.Task ReceiveLogSAsync(ServiceLibrary.DbModels.Log.EventLog eventLog)
    {
        return base.Channel.ReceiveLogSAsync(eventLog);
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://aei.polsl.pl/services/logger", ConfigurationName="ILogServiceAsync")]
public interface ILogServiceAsync
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://aei.polsl.pl/services/logger/ILogServiceAsync/ReceiveLogA", ReplyAction="http://aei.polsl.pl/services/logger/ILogServiceAsync/ReceiveLogAResponse")]
    void ReceiveLogA(ServiceLibrary.DbModels.Log.EventLog eventLog);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://aei.polsl.pl/services/logger/ILogServiceAsync/ReceiveLogA", ReplyAction="http://aei.polsl.pl/services/logger/ILogServiceAsync/ReceiveLogAResponse")]
    System.Threading.Tasks.Task ReceiveLogAAsync(ServiceLibrary.DbModels.Log.EventLog eventLog);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface ILogServiceAsyncChannel : ILogServiceAsync, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class LogServiceAsyncClient : System.ServiceModel.ClientBase<ILogServiceAsync>, ILogServiceAsync
{
    
    public LogServiceAsyncClient()
    {
    }
    
    public LogServiceAsyncClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public LogServiceAsyncClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LogServiceAsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public LogServiceAsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void ReceiveLogA(ServiceLibrary.DbModels.Log.EventLog eventLog)
    {
        base.Channel.ReceiveLogA(eventLog);
    }
    
    public System.Threading.Tasks.Task ReceiveLogAAsync(ServiceLibrary.DbModels.Log.EventLog eventLog)
    {
        return base.Channel.ReceiveLogAAsync(eventLog);
    }
}
namespace ServiceLibrary.DbModels.Log
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EventLog", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary.DbModels.Log")]
    public partial class EventLog : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressField;
        
        private string CallerSideField;
        
        private string ExceptionField;
        
        private string JsonField;
        
        private ServiceLibrary.DbModels.Log.NLogLevel LevelField;
        
        private int LineNumberField;
        
        private string LoggerField;
        
        private string MachineNameField;
        
        private string MessageField;
        
        private string StackTraceField;
        
        private System.Nullable<int> ThreadIdField;
        
        private System.DateTime TimeStampField;
        
        private string WindowsIdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Address
        {
            get
            {
                return this.AddressField;
            }
            set
            {
                this.AddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CallerSide
        {
            get
            {
                return this.CallerSideField;
            }
            set
            {
                this.CallerSideField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Exception
        {
            get
            {
                return this.ExceptionField;
            }
            set
            {
                this.ExceptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Json
        {
            get
            {
                return this.JsonField;
            }
            set
            {
                this.JsonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceLibrary.DbModels.Log.NLogLevel Level
        {
            get
            {
                return this.LevelField;
            }
            set
            {
                this.LevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LineNumber
        {
            get
            {
                return this.LineNumberField;
            }
            set
            {
                this.LineNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Logger
        {
            get
            {
                return this.LoggerField;
            }
            set
            {
                this.LoggerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MachineName
        {
            get
            {
                return this.MachineNameField;
            }
            set
            {
                this.MachineNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace
        {
            get
            {
                return this.StackTraceField;
            }
            set
            {
                this.StackTraceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ThreadId
        {
            get
            {
                return this.ThreadIdField;
            }
            set
            {
                this.ThreadIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime TimeStamp
        {
            get
            {
                return this.TimeStampField;
            }
            set
            {
                this.TimeStampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WindowsId
        {
            get
            {
                return this.WindowsIdField;
            }
            set
            {
                this.WindowsIdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NLogLevel", Namespace="http://schemas.datacontract.org/2004/07/ServiceLibrary.DbModels.Log")]
    public enum NLogLevel : byte
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trace = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warn = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fatal = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Off = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Custom = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Apt = 8,
    }
}
